### PR TITLE
DS-549 - gap tokens

### PR DESCRIPTION
**Pull request by monikaracka**

### CODE REVIEW

**Comment by zuzannanap** [comment]
Button is a bit lower and narrower (i guess it's not related with gaps - i guess the problem here is border)

**Comment by zuzannanap** [comment]
on this branch:
image
on main storybook:
image

**Comment by zuzannanap** [comment]
Gap doesn't work in Radio
image

**Comment by zuzannanap** [comment]
Gaps in stepper are different

image

image

**Comment by zuzannanap** [comment]
DatePicker doesn't work for me in storybook (docs are ok, but it doesn't dislay when i click on "Datepicker" - > "Datepicker"

**Comment by zuzannanap** [comment]
Input Autocomplete - bigger gap next to the icon
here:
image

on main storybook:
image

**Review by zuzannanap — CHANGES_REQUESTED** [review]

**Comment by monikaracka** [comment]
> Gaps in stepper are different
> 
> image image

I don't see this. Everything looks good.

**Comment by monikaracka** [comment]
> DatePicker doesn't work for me in storybook (docs are ok, but it doesn't dislay when i click on "Datepicker" - > "Datepicker"

I don't understand. I see datepicker in storybook after click docs and datepicker.

**Review by zuzannanap — APPROVED** [review]

**Pull request closed without merging**
